[package]
name = "pause-emitter"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
humantime = "2.1.0"
pnet = "0.35.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[lints]
workspace = true
